modLoader = "javafml"
loaderVersion = "[43,)"
license = "All rights reserved"
logoFile = "assets/perpetual_durability/icon/perpetual_durability.png"
issueTrackerURL = "https://github.com/ladylexxie/Perpetual-Durability/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "LadyLexxie"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version},1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kubejs"
mandatory = false
versionRange = "[${kubejs_version},)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "roughlyenoughitems"
mandatory = false
versionRange = "[${rei_version},)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jei"
mandatory = false
versionRange = "[${jei_version},)"
ordering = "BEFORE"
side = "BOTH"
