modLoader = "javafml"
loaderVersion = "[43,)"
license = "All rights reserved"
logoFile = "perpetual_durability.png"
issueTrackerURL = "https://github.com/ladylexxie/Perpetual-Durability/issues"

[[mods]]
modId = "${mod_id}"
version = "${file.jarVersion}"
displayName = "${mod_name}"
authors = "LadyLexxie"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.19.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kubejs"
mandatory = false
versionRange = "[${kubejs_version},)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "roughlyenoughitems"
mandatory = false
versionRange = "[${rei_version},)"
ordering = "BEFORE"
side = "BOTH"
