modLoader = "javafml"
loaderVersion = "[47,)"
license = "All rights reserved"
logoFile = "assets/perpetual_durability/icon/perpetual_durability.png"
issueTrackerURL = "https://github.com/ladylexxie/Perpetual-Durability/issues"

[[mods]]
modId = "perpetual_durability"
version = "${version}"
displayName = "Perpetual Durability"
authors = "LadyLexxie"
description = "A mod that adds a way to make items unbreakable"

[[dependencies.perpetual_durability]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.perpetual_durability]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version},1.20.1)"
ordering = "NONE"
side = "BOTH"

[[dependencies.perpetual_durability]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.perpetual_durability]]
modId = "cloth_config"
mandatory = true
versionRange = "[${cloth_config_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.perpetual_durability]]
modId = "roughlyenoughitems"
mandatory = false
versionRange = "[${rei_version},)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.perpetual_durability]]
modId = "jei"
mandatory = false
versionRange = "[${jei_version},)"
ordering = "BEFORE"
side = "BOTH"
