modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"
[[mods]]
modId="perpetual_durability"
version="${file.jarVersion}"
displayName="Perpetual Durability"
logoFile="perpetual_durability.png"
authors="LadyLexxie"
description='''
'''
[[dependencies.perpetual_durability]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.perpetual_durability]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,]"
    ordering="NONE"
    side="BOTH"
