modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="perpetual_durability"
version="${file.jarVersion}"
displayName="Perpetual Durability"
logoFile="perpetual_durability.png"
authors="LadyLexxie"
description='''
'''
[[dependencies.perpetual_durability]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.perpetual_durability]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
