modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
[[mods]]
modId="perpetual_durability"
version="${file.jarVersion}"
displayName="Perpetual Durability"
logoFile="perpetual_durability.png"
authors="LadyLexxie"
description='''
'''
[[dependencies.perpetual_durability]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.perpetual_durability]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
