name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: [ Bug ]
body:
  - type: dropdown
    id: mod-version
    attributes:
      label: Mod Version
      description: What version of the mod are you using?
      options:
        - 1.3.0
        - 1.2.1
        - 1.2.0
        - 1.1.0
        - 1.0.0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Please give a thorough explanation of what happened. Attach/Link relevant images/files in relation to the issue.
      placeholder: Tell me what you see!
    validations:
      required: true

  - type: input
    id: logs
    attributes:
      label: Crash Log
      description: Please upload your crash log to [GitHub Gist](https://gist.github.com/) and leave the link here.
      placeholder: https://gist.github.com/
    validations:
      required: true
