blank_issues_enabled: false
contact_links:
  - name: Team Resourceful Discord
    url: https://discord.gg/resourcefulbees
    about: Feel free to join the server and ping me, if you want to get in touch!
