name: Question
description: Ask me a question!
title: "[Question]: "
labels: [ Question ]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like to know?
      description: Please write your question here and it will be answered as soon as possible!
    validations:
      required: true
